using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MottuApi.Migrations
{
    /// <inheritdoc />
    public partial class FixOracleCaseSensitivity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Dropar e recriar tabelas com nomes em maiúsculas para compatibilidade com Oracle
            // Isso resolve o problema de case-sensitivity do Oracle
            
            // 1. Dropar tabelas existentes (se existirem)
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE ""Locacoes"" CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE LOCACOES CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE ""Clientes"" CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE ""Motos"" CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE MOTOS CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            // 2. Recriar tabelas em maiúsculas (padrão Oracle)
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE MOTOS (
                        ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                        ANO NUMBER(10) NOT NULL,
                        MODELO NVARCHAR2(2000) NOT NULL,
                        PLACA NVARCHAR2(450) NOT NULL,
                        STATUS NUMBER(10) NOT NULL,
                        CONSTRAINT PK_MOTOS PRIMARY KEY (ID)
                    )';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IX_MOTOS_PLACA ON MOTOS (PLACA)';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE CLIENTES (
                        ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                        NOME NVARCHAR2(2000) NOT NULL,
                        CPF NVARCHAR2(450) NOT NULL,
                        DATANASCIMENTO NVARCHAR2(10) NOT NULL,
                        NUMEROCNH NVARCHAR2(450) NOT NULL,
                        TIPOCNH NUMBER(10) NOT NULL,
                        CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
                    )';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IX_CLIENTES_CPF ON CLIENTES (CPF)';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX IX_CLIENTES_NUMEROCNH ON CLIENTES (NUMEROCNH)';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE TABLE LOCACOES (
                        ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
                        DATAINICIO TIMESTAMP(7) NOT NULL,
                        DATAFIMPREVISTA TIMESTAMP(7) NOT NULL,
                        DATAFIMREAL TIMESTAMP(7),
                        VALORDIARIA NUMBER(18,2) NOT NULL,
                        VALORTOTAL NUMBER(18,2),
                        STATUS NUMBER(10) NOT NULL,
                        CLIENTEID NUMBER(10) NOT NULL,
                        MOTOID NUMBER(10) NOT NULL,
                        CONSTRAINT PK_LOCACOES PRIMARY KEY (ID),
                        CONSTRAINT FK_LOCACOES_CLIENTES_CLIENTEID FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES(ID),
                        CONSTRAINT FK_LOCACOES_MOTOS_MOTOID FOREIGN KEY (MOTOID) REFERENCES MOTOS(ID)
                    )';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE INDEX IX_LOCACOES_CLIENTEID ON LOCACOES (CLIENTEID)';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'CREATE INDEX IX_LOCACOES_MOTOID ON LOCACOES (MOTOID)';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE LOCACOES CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
            
            migrationBuilder.Sql(@"
                BEGIN
                    EXECUTE IMMEDIATE 'DROP TABLE MOTOS CASCADE CONSTRAINTS';
                EXCEPTION
                    WHEN OTHERS THEN NULL;
                END;
            ");
        }
    }
}
